### ISSUE TITLE
Find a Design Library

### ISSUE THREAD

**Issue by ReshmiCode** [ReshmiCode/ProductiviTree#5]
**Describe the feature**
Find a design library we will use and understand how it works and how to change the theme colors.

**Feature Checklist**
- [x] Find a design library
- [x] Everyone review

**Comment by meganjtran** [comment]
combination of native base & native elements
- https://docs.nativebase.io/Components.html#Components (fab, most things)
- https://react-native-elements.github.io/react-native-elements/docs/overview.html (cards, hamburger menu)
- https://github.com/JesperLekland/react-native-svg-charts (activity charts!)
