### ISSUE TITLE
Design Day Presentation

### ISSUE THREAD

**Issue by SaloniSS** [ReshmiCode/ProductiviTree#9]
**Describe the feature**
Presentation for Design Day

**Expected behavior**
Refer to slack

**Feature Checklist**
- [x] Problem Statement
- [x] Technical Architecture
- [x] UX screenshots if appropriate

**Screenshots**

**Additional context**

**Comment by meganjtran** [comment]
Script and slides for presentation are finished, will complete video tonight

**Comment by meganjtran** [comment]
Video completed, uploaded, and added to presentation
